version: "3"
services:
  directus:
    image: directus/directus:10.10.0
    ports:
      - "8055:8055"
    volumes:
      - ./directus/database:/directus/database
      - ./directus/uploads:/directus/uploads
    environment:
      KEY: "nugraha-labib-secret-key"
      SECRET: "nugraha-labib-secret-secret"
      ADMIN_EMAIL: "admin@nugrahalabib.com"
      ADMIN_PASSWORD: "password123"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true"
      CORS_ENABLED: "true"
      CORS_ORIGIN: "true"
